DISABLE_AUTO_TITLE="true"
PROMPT="[%n@%m %~]# "
skip_global_compinit=1

setopt ALWAYS_TO_END
setopt AUTO_LIST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt INTERACTIVE_COMMENTS
setopt LIST_AMBIGUOUS
unsetopt AUTO_MENU
unsetopt BEEP
unsetopt MENU_COMPLETE
unsetopt PROMPT_SP

# Explicitly enable reverse search
bindkey '^R' history-incremental-search-backward
bindkey -v

# User configuration
export EDITOR=vim
export GOPATH=$HOME/Documents/workspace/go-lang
export HISTCONTROL=ignoredups:ignorespace
export HISTFILESIZE=500
export HISTSIZE=500
export KUBECONFIG=$HOME/.kube/config.prod:$HOME/.kube/config
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PAGER=less
export PATH="\
$GOPATH/bin:/snap/bin:\
$HOME/Library/Python/2.7/bin:\
/usr/local/sbin:\
/usr/local/Cellar/kubernetes-cli/1.15.0/bin:\
/usr/local/Cellar/golangci-lint/1.20.1/bin:\
/usr/local/Cellar/nmap/7.80_1/bin:\
/usr/local/Cellar/universal-ctags/HEAD-e216bb4/bin:\
$PATH"

alias cp='cp -v'
alias grep='grep --color=auto'
alias less='less -FSRXc'
alias ll='ls -FGlAhp'
alias mkdir='mkdir -v'
alias mv='mv -v'

