try
  silent! colorscheme PaperColor
endtry

filetype plugin on
highlight SpecialKey ctermfg=grey guifg=grey "tab&space

let NERDTreeShowHidden = 1
let NERDTreeWinSize = 40
let g:mustache_operators = 0
let g:vim_markdown_conceal = 0
let g:vim_markdown_no_default_key_mappings = 1
let loaded_netrwPlugin = 1
let mapleader = "\<Space>"
let skip_defaults_vim = 1
let g:gutentags_ctags_extra_args = [
  \ '--tag-relative=yes',
  \ '--fields=+ailmnS',
  \ '--languages=Python,Go',
\ ]

function! WinToLin() abort "convert line ends
  update
  e ++ff=dos
  setlocal ff=unix
  set fileencoding=utf8
  set nobomb
endfunction

function! TagsStatus() abort
  try
    return gutentags#statusline()
  catch
    return ""
  endtry
endfunction

nnoremap <Leader>b :buffers<CR>:buffer<Space>
nnoremap <Leader>f :NERDTreeFind<CR>
nnoremap <Leader>l :call WinToLin()<CR>
nnoremap <Leader>n :NERDTreeToggle<CR>
nnoremap <Leader>p :%!python -m json.tool<CR>
nnoremap <Leader>q :bp\|bd #<CR>
nnoremap <S-Tab> :bprevious<CR>
nnoremap <Tab> :bnext<CR>

autocmd BufEnter * if bufname('#') =~# "^NERD_tree_" && winnr('$') > 1 | b# | endif

if !has('nvim')
  if has('win32') || has('win64')
    set renderoptions^=type:directx
  else
    set term=$TERM "Make arrow and other keys work
  endif
endif
if &term == 'xterm' || &term == 'screen'
  set t_Co=256 "Enable 256 colors to stop the CSApprox warning and make xterm vim shine
endif
if has('clipboard')
  set clipboard^=unnamed "On mac and Windows, use * register for copy-paste
  if has('unnamedplus')  "When possible use + register for copy-paste
    set clipboard^=unnamedplus
  endif
endif
if exists('&ttyfast')
  set ttyfast
endif
if has('termguicolors')
  set notermguicolors
endif
if has('syntax')
  if &diff
    syntax off
  else
    syntax on
    syntax sync minlines=256
    set synmaxcol=256 "performance optimization
    set path+=**
  endif
endif
if v:version > 700
  set omnifunc=syntaxcomplete#Complete
endif
if has('statusline')
  set laststatus=2
  set statusline=%<%F\ %{TagsStatus()}%h%m%r%=%{\"[\".(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\").\"]\ \"}%{&fileformats}\ %-14.(%l,%c%V%)\ %P
  hi StatusLine ctermbg=black ctermfg=white guibg=black guifg=white
endif
if has('patch-8.1.0360')
  set diffopt=internal,algorithm:patience,indent-heuristic
endif

set background=light
set backspace=indent,eol,start
set encoding=utf-8
set fileencodings=utf-8,cp1251,koi8-r,cp866
set fileformats=unix
set hidden
set history=5
set hlsearch
set incsearch
set lazyredraw
set linespace=0
set list
set listchars=tab:•·,trail:•,nbsp:¤,extends:»,precedes:«
set matchtime=1
set modelines=0
set mouse= "disable mouse
set nobackup
set nofoldenable
set noswapfile
set notitle
set nowrap
set nowritebackup
set shiftwidth=4
set showbreak=¬
set showmatch
set tags=tags;/
set textwidth=0
set ttimeout
set ttimeoutlen=50
set undolevels=32
set viminfo=""
set wildignorecase
set wildmode=list:longest

set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

