syntax off

filetype plugin indent on

highlight Search ctermfg=white ctermbg=darkgray guifg=white guibg=darkgray
highlight Visual ctermfg=white ctermbg=darkgray guifg=white guibg=darkgray

let g:NERDTreeHijackNetrw = 1
let g:NERDTreeNodeDelimiter = "\u00a0" "remove ^G with `syntax off`
let g:NERDTreeShowHidden = 1
let g:NERDTreeStatusline = ""
let g:NERDTreeWinSize = 40
let g:ale_completion_enabled = 1
let g:loaded_netrwPlugin = 1
let g:mapleader = "\<Space>"
let g:mustache_operators = 0
let g:skip_defaults_vim = 1
let g:vim_markdown_conceal = 0
let g:vim_markdown_no_default_key_mappings = 1
let g:gutentags_ctags_extra_args = [
  \ "--fields=+ailmnS",
  \ "--languages=Python,PHP,Go",
  \ "--tag-relative=yes",
\ ]

function! WinToLin() abort "convert line ends
  update
  e ++ff=dos
  setlocal ff=unix
  set fileencoding=utf8
  set nobomb
endfunction

function! TagsStatus() abort
  try
    return gutentags#statusline()
  catch
    return ""
  endtry
endfunction

noremap <Leader>b :buffers<CR>:buffer<Space>
noremap <Leader>f :NERDTreeFind<CR>
noremap <Leader>l :call WinToLin()<CR>
noremap <Leader>n :NERDTreeToggle<CR>
noremap <Leader>p :%!python -m json.tool<CR>
noremap <Leader>q :bdelete<CR> "noremap <Leader>q :bprevious<bar>split<bar>bnext<bar>bdelete<CR> - workaround for nerdtree
noremap <Tab> :wincmd w<CR>

autocmd BufEnter * if bufname("#") =~# "^NERD_tree_" && winnr("$") > 1 | b# | endif

if !has("nvim")
  if has("win32") || has("win64")
    set renderoptions^=type:directx
  else
    set term=$TERM "Make arrow and other keys work
  endif
endif
if has("clipboard")
  set clipboard^=unnamed "On mac and Windows, use * register for copy-paste
  if has("unnamedplus")  "When possible use + register for copy-paste
    set clipboard^=unnamedplus
  endif
endif
if has("statusline")
  set laststatus=2
  set statusline=%<%F\ %{TagsStatus()}%h%m%r%=%{\"[\".(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\").\"]\ \"}%{&fileformats}\ %-14.(%l,%c%V%)\ %P
endif
try
  set omnifunc=ale#completion#OmniFunc
catch
  if v:version > 700
    set omnifunc=syntaxcomplete#Complete
  endif
endtry
try
  set commentary "enable commentary emulation in ideavim
catch
endtry

set background=light
set backspace=indent,eol,start
set belloff=all
set encoding=utf-8
set fileencodings=utf-8,cp1251,koi8-r,cp866
set fileformats=unix
set hidden
set history=5
set hlsearch
set ignorecase
set incsearch
set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz
set lazyredraw
set linebreak
set linespace=0
set list
set listchars=tab:•·,trail:•,nbsp:¤,extends:¦,precedes:¦
set matchtime=1
set modelines=0
set mouse=a
set nobackup
set noerrorbells
set nofoldenable
set noswapfile
set notermguicolors
set notitle
set nowrap
set nowritebackup
set shiftwidth=4
set shortmess=atOI
set showbreak=¬
set showmatch
set smartcase
set t_Co=256 "Enable 256 colors to stop the CSApprox warning and make xterm vim shine
set tags=tags;/
set textwidth=0
set ttimeout
set ttimeoutlen=50
set ttyfast
set undolevels=32
set viminfo=""
set visualbell
set wildignorecase
set wildmode=list:longest

